import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="header">
          <p>(Root Layout)</p>
          <h1>Header</h1>
        </div>
        <div id="root">
          {children}
        </div>
        </body>
    </html>
  )
}
